name: Deploy to Heroku

on:
  push:
    branches:
      - productionReady

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to push full history if needed

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "dvision-security"
        run: |
          # Add Heroku remote with API key authentication
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

          # Push the productionReady branch to Heroku's main branch
          git push heroku productionReady:main -f
